### ISSUE TITLE
[Feature Request] - Option to search before dialing/calling. 

### ISSUE THREAD

**Issue by BotMister** [DreadedLama/Simple-Dialer#1]
It would be great if there was an option where before dialing you could search truecaller database for info on the number. As of now, it starts the search once you're already dialing or when receiving calls.

Thanks for your great work by the way. Loving this app.

**Comment by DreadedLama** [comment]
Hey @BotMister,
The feature is already on my to-do list for the app, but it requires a few changes in the code as to how I'm fetching the name. working on it.
Thanks for trying the app.

**Comment by DreadedLama** [comment]
Implemented in the 5.17.3.1 release
