### ISSUE TITLE
[Bug] - New update broke Truecaller functionality.

### ISSUE THREAD

**Issue by BotMister** [DreadedLama/Simple-Dialer#2]
After updating to the new version 5.17.3.1 , Truecaller functionality no longer works. I tried on 2 different phones and still doesn't work. Both the Search and the normal Truecaller function on incoming/outgoing calls don't work.

**Comment by DreadedLama** [comment]
It seems to work fine. Just retested it again. Can you please confirm if your token is working with the old release but now working with the new one?

**Comment by BotMister** [comment]
> It seems to work fine. Just retested it again. Can you please confirm if your token is working with the old release but now working with the new release?

Just tested with the old release and it's also not working. What happened to the token? It was working fine right before I updated.

**Comment by DreadedLama** [comment]
The token has expired. Please get a new token by installing the truecaller app again and following the steps.

**Comment by BotMister** [comment]
Thank you, it works great with a new token... do you know if this is something that happens regularly where the Truecaller ID expires?
