### ISSUE TITLE
truecaller doesn't seem to be working in new update

### ISSUE THREAD

**Issue by Riderzzzzz** [DreadedLama/Simple-Dialer#3]
So I followed all the provided steps. Installed truecaller, setup my profile allowing perms. Settings>privacy center>download my data. Viewed the json file using file manager editer. Copy and pasted the long "id" that is above "created at" into simple dialer settings>truecaller and put token and country code. (Tried both 44 and +44 didn't work) 
Also to mention, I installed both the latest and 11.84.7 versions of truecaller, but the id still doesn't work.

Do I have to reboot my device?

Thanks btw for the truecaller intergration :)

**Comment by DreadedLama** [comment]
The country code has to be like "IN", "US", "NG". I should have mentioned that correctly in the release description. Try with the Country code in alphabets and not in numbers. I'm planning to make this process smooth in future releases.

**Comment by Riderzzzzz** [comment]
Hi, 

Sorry for not editing my previous comment. I realized that since it was in file editor and changed the country code to "GB" as I'm located in the UK. 

I'm not sure this helps but on the dialpad, I do get a blue search function on the bottom right but that doesn't do anything for me.

**Comment by DreadedLama** [comment]
Please provide a sample UK number with the country code.  Let me take a look

**Comment by Riderzzzzz** [comment]
+44700 900000

Just an example UK number.

**Comment by Riderzzzzz** [comment]
Oh ok. That's interesting, i mean my number is 10 digits +447877****** so you are right (My bad).

I have tested it 3 times and I've been getting different tokens from the truecaller app. I also did wait for a week as I thought that it may need time to register the token or get it working? But idk, I think it may be an issue on my end.

**Comment by DreadedLama** [comment]
My token hasn't changed for more than a year. Not sure if truecaller has changed anything after that.
I'll close the request for now. Open the issue again if you face any problems.
