### ISSUE TITLE
ERROR : Request failed with status code 451

### ISSUE THREAD

**Issue by djmeero** [DreadedLama/Simple-Dialer#4]
Are there any limitations while using european auth tokens from Truecaller?

I got my token using italian phone number and country code "IT". When testing number in format "+391234567890" I don't get any result... I tried using the truecallerjs npm package on Windows PC and failing on sending OTP with error:
    },
    data: {
      status: 45101,
      message: 'Unavailable for legal reasons',
      domain: 'eu'
    }
Using the alternative procedure setting the token by using provided .json file I get error "Request failed with status code 451".
I have a friend from ASIA and tried using his token and country code and it partially worked.. when I lookup italian number I get just carrier info but "Unknown name".

**Comment by DreadedLama** [comment]
I am not sure if there is any limitations with the European auth. Not in that region, so can't comment on that.

If Truecaller does not return any name in the response, in this case, I display "Unknown". So I guess, that is the reason you are getting "Unknown" name.
