### ISSUE TITLE
[Bug] - Dialpad does not function during calls

### ISSUE THREAD

**Issue by BotMister** [DreadedLama/Simple-Dialer#5]
I noticed the dialpad will not work during phone calls if I uncheck the setting "Enable beeps on dialpad button clicks". It works fine if that option is checked.
I'm guessing this is a bug coming from SimpleDialer directly, not sure if they have fixed it yet but I thought it's worth mentioning here. 
Thanks

**Comment by DreadedLama** [comment]
Yes, I have noticed this issue too. Since it is an upstream issue, fixing it is out of this project's scope. Please report the issue in the main repo.
Thanks.

**Comment by BotMister** [comment]
Seems like it's fixed in the latest version 5.17.6

**Comment by DreadedLama** [comment]
Oh, did not check the latest version. Will update the project once I get time.
