### ISSUE TITLE
Call Recorder

### ISSUE THREAD

**Issue by subhashis-barad** [DreadedLama/Simple-Dialer#6]
Add a call recorder Plox

**Comment by DreadedLama** [comment]
Call recording needs root, without it it's not possible. If your phone is rooted then there are already better alternatives available. Moreover adding call recorder is out of the scope of this project.

**Comment by subhashis-barad** [comment]
Ohh, thanks for looking for it, though I'm root user, I didn't find any Foss alternatives.

Thank you

**Comment by DreadedLama** [comment]
You can try Magisk modules to replace your dialer with some other dialer with call recording support or use LSPosed to enable it in Google dialer. A quick google search will provide you with plenty of alternatives. 
Thanks

**Comment by subhashis-barad** [comment]
![Uploading Screenshot_20230506-114622_Phone.png…]()
