### ISSUE TITLE
Adding notification caller id

### ISSUE THREAD

**Issue by rohit-burman** [DreadedLama/Simple-Dialer#7]
Can add notification like Truecaller caller id . So when there is an incoming call we can get a box overlay on the screen with caller details. Without using this dialer as default for phone calls

**Comment by DreadedLama** [comment]
I tried adding the caller Id popup in my other project(BaseCaller) but ran into some issues. If I ever plan to add this feature, it'll be a new project entirely and not in this dialer. 
As of now, I don't have a plan to add the caller id to this dialer.
Thanks
