### ISSUE TITLE
[Feature Request] - Call Notes

### ISSUE THREAD

**Issue by BugsWorld** [DreadedLama/Simple-Dialer#8]
Not sure if this app is still being updated but I still use it and would LOVE to have an option to Add and edit notes or reminders to calls to during or after call ended.

Example of an app that has this feature: [ACR Phone](https://play.google.com/store/apps/details?id=com.nll.cb)

**Comment by DreadedLama** [comment]
Hey @BugsWorld,
As of now, I'm not working actively on this project. Adding the notes feature to the dialer is out of this project's scope. This fork is to add the truecaller info to the app. You can request this feature in the original repo, once it gets added there, I'll happily merge the changes in my fork from there.
Happy to hear you love it.

**Comment by BugsWorld** [comment]
You're right, it absolutely makes sense. I should have mentioned this on the original repo. Any way you can get it up to date with the current version? There are some bug fixes. Thanks a lot for your work.

**Comment by DreadedLama** [comment]
The latest upstream changes have been merged and released.
