### ISSUE TITLE
Not getting Truecaller id in the downloaded json

### ISSUE THREAD

**Issue by shreya-shah** [DreadedLama/Simple-Dialer#9]
Has the field changed or it can no longer be available? I am not sure how should I integrate Truecaller.

**Comment by DreadedLama** [comment]
Truecaller has removed the id field from the json after noticing this app was using it to fetch data from their servers. Typical Truecaller Stuff. 
There is an alternate approach to get the auth token but it uses root permissions. I have updated the steps accordingly.
